#!/bin/bash

# Platform-Specific API Configuration Helper

echo "🔧 API Configuration Helper"
echo ""
echo "Your backend API is ✅ running and responding on localhost:4000"
echo ""
echo "The issue is that your mobile app can't reach it."
echo "This depends on what platform you're testing on:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📱 Choose your setup:"
echo ""
echo "1️⃣  iOS SIMULATOR"
echo "   ✓ app.json should have: http://localhost:4000"
echo "   ✓ Current setting is likely correct"
echo "   ✓ Restart the app with: npm run ios"
echo ""
echo "2️⃣  ANDROID EMULATOR"
echo "   ✓ app.json needs to be changed to: http://10.0.2.2:4000"
echo "   ✓ Run this command:"
echo "     sed -i '' 's|\"apiBaseUrl\": \"[^\"]*\"|\"apiBaseUrl\": \"http://10.0.2.2:4000\"|' app.json"
echo "   ✓ Then restart: npm run android"
echo ""
echo "3️⃣  PHYSICAL DEVICE (iPhone/Android on same WiFi)"
echo "   ✓ First, get your machine's local IP:"
echo "     ipconfig getifaddr en0"
echo "   ✓ Then update app.json, replacing YOUR_IP:"
echo "     \"apiBaseUrl\": \"http://YOUR_IP:4000\""
echo "   ✓ Ensure phone and dev machine are on same WiFi"
echo "   ✓ Restart the app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Current app.json API URL:"
grep -o '"apiBaseUrl": "[^"]*"' app.json || echo "   (not found)"
echo ""
echo "After making changes, restart the app and look for:"
echo "  ✅ [API Response] <-- 200 /api/experiences"
echo "  ❌ NOT seeing SAGA_ERROR or Network Error"
echo ""
